// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[derive(std::clone::Clone, std::cmp::PartialEq)]
pub struct ListBisonInput {
    #[allow(missing_docs)] // documentation missing in model
    pub herd: std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub stage: std::string::String,
}
impl ListBisonInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn herd(&self) -> &str {
        use std::ops::Deref;
        self.herd.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn stage(&self) -> &str {
        use std::ops::Deref;
        self.stage.deref()
    }
}
impl std::fmt::Debug for ListBisonInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut formatter = f.debug_struct("ListBisonInput");
        formatter.field("herd", &self.herd);
        formatter.field("stage", &self.stage);
        formatter.finish()
    }
}
/// See [`ListBisonInput`](crate::input::ListBisonInput)
pub mod list_bison_input {
    /// A builder for [`ListBisonInput`](crate::input::ListBisonInput)
    #[non_exhaustive]
    #[derive(std::default::Default, std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
    pub struct Builder {
        pub(crate) herd: std::option::Option<std::string::String>,
        pub(crate) stage: std::option::Option<std::string::String>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn herd(mut self, input: impl Into<std::string::String>) -> Self {
            self.herd = Some(input.into());
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn set_herd(mut self, input: std::option::Option<std::string::String>) -> Self {
            self.herd = input;
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn stage(mut self, input: impl Into<std::string::String>) -> Self {
            self.stage = Some(input.into());
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn set_stage(mut self, input: std::option::Option<std::string::String>) -> Self {
            self.stage = input;
            self
        }
        /// Consumes the builder and constructs a [`ListBisonInput`](crate::input::ListBisonInput)
        pub fn build(
            self,
        ) -> std::result::Result<crate::input::ListBisonInput, aws_smithy_http::operation::BuildError>
        {
            Ok(crate::input::ListBisonInput {
                herd: self.herd.unwrap_or_default(),
                stage: self.stage.unwrap_or_default(),
            })
        }
    }
}
impl ListBisonInput {
    /// Creates a new builder-style object to manufacture [`ListBisonInput`](crate::input::ListBisonInput)
    pub fn builder() -> crate::input::list_bison_input::Builder {
        crate::input::list_bison_input::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(std::clone::Clone, std::cmp::PartialEq)]
pub struct CreateBisonInput {
    #[allow(missing_docs)] // documentation missing in model
    pub herd: std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub name: std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub rank: i32,
    #[allow(missing_docs)] // documentation missing in model
    pub tags: std::option::Option<std::vec::Vec<crate::model::BisonTag>>,
}
impl CreateBisonInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn herd(&self) -> &str {
        use std::ops::Deref;
        self.herd.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn name(&self) -> &str {
        use std::ops::Deref;
        self.name.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn rank(&self) -> i32 {
        self.rank
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn tags(&self) -> std::option::Option<&[crate::model::BisonTag]> {
        self.tags.as_deref()
    }
}
impl std::fmt::Debug for CreateBisonInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut formatter = f.debug_struct("CreateBisonInput");
        formatter.field("herd", &self.herd);
        formatter.field("name", &self.name);
        formatter.field("rank", &self.rank);
        formatter.field("tags", &self.tags);
        formatter.finish()
    }
}
/// See [`CreateBisonInput`](crate::input::CreateBisonInput)
pub mod create_bison_input {
    /// A builder for [`CreateBisonInput`](crate::input::CreateBisonInput)
    #[non_exhaustive]
    #[derive(std::default::Default, std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
    pub struct Builder {
        pub(crate) herd: std::option::Option<std::string::String>,
        pub(crate) name: std::option::Option<std::string::String>,
        pub(crate) rank: std::option::Option<i32>,
        pub(crate) tags: std::option::Option<std::vec::Vec<crate::model::BisonTag>>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn herd(mut self, input: impl Into<std::string::String>) -> Self {
            self.herd = Some(input.into());
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn set_herd(mut self, input: std::option::Option<std::string::String>) -> Self {
            self.herd = input;
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn name(mut self, input: impl Into<std::string::String>) -> Self {
            self.name = Some(input.into());
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn set_name(mut self, input: std::option::Option<std::string::String>) -> Self {
            self.name = input;
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn rank(mut self, input: i32) -> Self {
            self.rank = Some(input);
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn set_rank(mut self, input: std::option::Option<i32>) -> Self {
            self.rank = input;
            self
        }
        /// Appends an item to `tags`.
        ///
        /// To override the contents of this collection use [`set_tags`](Self::set_tags).
        ///
        pub fn tags(mut self, input: crate::model::BisonTag) -> Self {
            let mut v = self.tags.unwrap_or_default();
            v.push(input);
            self.tags = Some(v);
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn set_tags(
            mut self,
            input: std::option::Option<std::vec::Vec<crate::model::BisonTag>>,
        ) -> Self {
            self.tags = input;
            self
        }
        /// Consumes the builder and constructs a [`CreateBisonInput`](crate::input::CreateBisonInput)
        pub fn build(
            self,
        ) -> std::result::Result<
            crate::input::CreateBisonInput,
            aws_smithy_http::operation::BuildError,
        > {
            Ok(crate::input::CreateBisonInput {
                herd: self.herd.unwrap_or_default(),
                name: self.name.unwrap_or_default(),
                rank: self.rank.unwrap_or_default(),
                tags: self.tags,
            })
        }
    }
}
impl CreateBisonInput {
    /// Creates a new builder-style object to manufacture [`CreateBisonInput`](crate::input::CreateBisonInput)
    pub fn builder() -> crate::input::create_bison_input::Builder {
        crate::input::create_bison_input::Builder::default()
    }
}
